language: rust
dist: xenial
script:
  - 'if [ "$TRAVIS_RUST_VERSION" == "1.34.0" ]; then cargo update -p bytes --precise 0.4.12; fi'
  - 'cargo test --no-default-features'
  - 'cargo test --all-features'
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --all-features --all-targets; fi'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

env: # important!
matrix:
  include:
    - rust: 1.34.0
    - rust: 1.39.0
    - rust: stable
    - rust: nightly
      env: MAY_FAIL=true
    - rust: 1.39.0
      os: osx
  allow_failures:
    - env: MAY_FAIL=true
