language: rust
sudo: false
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then cargo update; fi'
  - 'cargo test --no-default-features'
  - 'cargo test --all-features'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

rust: beta
env: # important!
matrix:
  include:
    - rust: beta
      os: osx
      env: WITH_LOCK=true
    - rust: beta
      env: WITH_LOCK=true
    - rust: nightly
      env: WITH_LOCK=true
    - rust: nightly
      env: MAY_FAIL=true
  allow_failures:
    - env: MAY_FAIL=true
