[package]
name          = "olio"
version       = "0.1.0"
authors       = ["David Kellum <dek-oss@gravitext.com>"]
license       = "MIT/Apache-2.0"
description   = "Miscellaneous I/O utilities"
documentation = "https://docs.rs/olio"
repository    = "https://github.com/dekellum/olio"
readme        = "README.md"
keywords      = ["file", "fs", "io"]
categories    = ["filesystem"]
exclude       = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
]

[badges]
travis-ci = { repository = "dekellum/olio" }

[dependencies]
memmap     = { version = ">=0.6.2, <2", optional = true }

[dev-dependencies]
bytes      = ">=0.4.6, <2"
tempfile   = ">=2.2.0, <4"

[features]
default = ["memmap"]

[lib]
doctest = false

[package.metadata.docs.rs]
features = ["memmap"]
